spring:
  config:
    activate:
      on:profile: "qa"

build:
  version: "2.0"


cards:
  message: "Welcome to Samith28shetty loans qa version"
  ContactDetails:
    - name: "samith Shetty"
    - email: "samith@gmail.com"
  onCallSupport:
    -(555)555-1234
    -(555)523-1345



